AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance for Tomcat environment (recreated from existing env)

Parameters:
  KeyName:
    Description: SSH key pair
    Type: String
    Default: ramirez27

Resources:

  TomcatInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0cfab433ce39f6cf3
      KeyName: !Ref KeyName
      IamInstanceProfile: EC2-CloudwatchlogsRole
      SubnetId: subnet-0056d8978b8d036b7
      SecurityGroupIds:
        - sg-0c6327b7fa160bc86
        - sg-060611c22bd5583c5
      Tags:
        - Key: Name
          Value: Tomcat-env-CF

  TomcatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  TomcatEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref TomcatInstance
      EIP: 52.2.50.44

