AWSTemplateFormatVersion: '2010-09-09'
Description: Elastic Beanstalk Application + Environment para Tomcat 11 con Corretto 25.

Parameters:
  ApplicationName:
    Type: String
    Default: tomcat

  EnvironmentName:
    Type: String
    Default: Tomcat-env

  PlatformArn:
    Type: String
    Default: "arn:aws:elasticbeanstalk:us-east-1::platform/Tomcat 11 with Corretto 25 running on 64bit Amazon Linux 2023/5.9.0"

  InstanceType:
    Type: String
    Default: t2.micro

  SecurityGroups:
    Type: CommaDelimitedList
    Default: sg-060611c22bd5583c5   # Tomcat-EB / tomcat-sg

Resources:

  TomcatApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Ref ApplicationName
      Description: Aplicación Tomcat manejada por CloudFormation.

  TomcatEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref TomcatApplication
      EnvironmentName: !Ref EnvironmentName
      Description: Environment Tomcat creado vía CloudFormation.
      PlatformArn: !Ref PlatformArn
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: !Ref InstanceType
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: SecurityGroups
          Value: !Join [ ",", !Ref SecurityGroups ]
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: LoadBalanced  # o SingleInstance si quieres 1 sola instancia

Outputs:
  ElasticBeanstalkAppName:
    Description: Nombre de la aplicación EB
    Value: !Ref TomcatApplication

  ElasticBeanstalkEnvName:
    Description: Nombre del environment EB
    Value: !Ref TomcatEnvironment

