AWSTemplateFormatVersion: "2010-09-09"
Description: "Route 53 records for program-as.com"

Parameters:
  HostedZoneId:
    Type: String
    Description: "Hosted Zone ID for program-as.com"
    Default: Z05140832S813V0VFA5C0   # <-- del screenshot

  DomainName:
    Type: String
    Default: program-as.com

  EBEndpoint:
    Type: String
    Description: "Elastic Beanstalk endpoint"
    Default: tomcat-env.eba-hrki2mdq.us-east-1.elasticbeanstalk.com
    # cámbialo si tu endpoint cambia

Resources:

  ARecordRoot:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !Ref EBEndpoint
        HostedZoneId: Z3DZXE0Q79N41H # Hosted zone ID fijo de Elastic Beanstalk ALB

  VerificationCNAME:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: "_63e70d2.xxx.program-as.com"   # <-- ponlo EXACTO como aparece en tu record
      Type: CNAME
      TTL: "300"
      ResourceRecords:
        - "f54741947b41c56cfb.example.acm-validations.aws"

Outputs:
  DomainURL:
    Value: !Sub "http://${DomainName}"
    Description: "URL final del dominio"

